{% set name = "fuzzysearch" %}
{% set version = "0.7.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/taleinat/fuzzysearch/archive/v{{ version }}.tar.gz
  sha256: 9988136caef59687d203f8c494ae870a171a40198b53fc87a06b485916d105df

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - cython
  run:
    - python
    - attrs >=19.3

test:
  imports:
    - fuzzysearch
  source_files:
    - tests
  commands:
    - "python -m unittest discover tests -v"

about:
  home: https://github.com/taleinat/fuzzysearch
  dev_url: https://github.com/taleinat/fuzzysearch
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Easy fuzzy search that just works, fast!

extra:
  recipe-maintainers:
    - klauer
