{% set name = "fuzzysearch" %}
{% set version = "0.7.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/taleinat/fuzzysearch/archive/v{{ version }}.tar.gz
  sha256: 6c88b85468f2961c04a16da727cf9af77f6130806c558a8416ca84f950c231a8

build:
  number: 5
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - cython
  run:
    - python
    - attrs >=19.3

test:
  imports:
    - fuzzysearch

about:
  home: https://github.com/taleinat/fuzzysearch
  dev_url: https://github.com/taleinat/fuzzysearch
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Easy fuzzy search that just works, fast!

extra:
  recipe-maintainers:
    - klauer
