{% set name = "fuzzysearch" %}
{% set version = "0.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/taleinat/fuzzysearch/archive/v{{ version }}.tar.gz
  sha256: 977b3570f6967c29da9733c9f7e4851052e510d649e44e82a3c1b304ccb3eb02

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - cython
    - setuptools
  run:
    - python
    - attrs >=19.3

test:
  imports:
    - fuzzysearch

about:
  home: https://github.com/taleinat/fuzzysearch
  dev_url: https://github.com/taleinat/fuzzysearch
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Easy fuzzy search that just works, fast!

extra:
  recipe-maintainers:
    - klauer
